"""
compressor.py — Stage 5: Clause Compression.

Converts long sentences into compact forms by removing subordinate clauses,
reducing passive voice, and simplifying sentence starts.
"""

import re
from typing import List

from app.utils.text_utils import split_sentences


def compress(text: str, level: float = 0.7) -> str:
    """
    Apply clause compression to text.

    Args:
        text: Pre-processed text.
        level: 0.0–1.0 compression intensity.
               0.0 = no compression, 1.0 = maximum compression.

    Returns:
        Compressed text.
    """
    sentences = split_sentences(text)
    compressed: List[str] = []

    for sent in sentences:
        result = sent

        # Always apply: sentence-start simplification
        result = _simplify_sentence_start(result)

        if level >= 0.3:
            result = _remove_subordinate_clauses(result)

        if level >= 0.5:
            result = _reduce_passive_voice(result)

        if level >= 0.7:
            result = _compress_relative_clauses(result)

        if level >= 0.9:
            result = _remove_parentheticals(result)

        result = result.strip()
        if result:
            compressed.append(result)

    return ' '.join(compressed)


# ── Transformation functions ─────────────────────────────────────────────────

def _simplify_sentence_start(sent: str) -> str:
    """
    Remove verbose sentence starters.
    'The system should be able to generate...' → 'Generate...'
    """
    patterns = [
        # "The system/it/you should/must/can/will be able to [verb]"
        (r'^(The\s+\w+\s+)?(?:should|must|can|will|shall)\s+be\s+able\s+to\s+',
         ''),
        # "The system/it should/must [verb]"
        (r'^(The\s+\w+\s+)?(?:should|must|shall|will|can)\s+', ''),
        # "It is necessary/important/required/essential to"
        (r'^It\s+is\s+(?:necessary|important|required|essential|crucial|vital)\s+'
         r'(?:to|that\s+(?:you|we|the\s+\w+))\s+', ''),
        # "You are expected/required to"
        (r'^(?:You|We)\s+(?:are|is)\s+(?:expected|required|supposed)\s+to\s+', ''),
        # "What you need to do is"
        (r'^What\s+(?:you|we)\s+need\s+to\s+do\s+is\s+', ''),
        # "The goal/purpose/objective is to"
        (r'^The\s+(?:goal|purpose|objective|aim|idea)\s+(?:is|here\s+is)\s+to\s+',
         ''),
        # "I would like you to" / "I want you to"
        (r'^I\s+(?:would\s+like|want|need)\s+(?:you\s+)?to\s+', ''),
    ]

    for pattern, replacement in patterns:
        new_sent = re.sub(pattern, replacement, sent, flags=re.IGNORECASE)
        if new_sent != sent:
            # Capitalize first letter after transformation
            if new_sent and new_sent[0].islower():
                new_sent = new_sent[0].upper() + new_sent[1:]
            return new_sent

    return sent


def _remove_subordinate_clauses(sent: str) -> str:
    """Remove non-essential subordinate clauses."""
    # ", which is/are/was ..." → remove up to next comma or period
    sent = re.sub(
        r',\s*which\s+(?:is|are|was|were|has|have|had)\s+[^,\.]+[,\.]?',
        '', sent,
    )
    # ", that is, ..." → remove
    sent = re.sub(r',\s*that is,\s*', ', ', sent)

    # "..., especially when/if ..." → remove trailing clause
    sent = re.sub(
        r',\s*(?:especially|particularly|notably)\s+(?:when|if|where)\s+.*$',
        '.', sent,
    )

    return sent


def _reduce_passive_voice(sent: str) -> str:
    """
    Convert simple passive constructions to active where possible.
    'X is generated by the system' → 'The system generates X' not feasible
    without knowing the subject, so we simplify:
    'should be [past participle]' → '[base verb]'
    """
    # "should/must/can be [verb]ed" → "[verb]"
    def _passive_to_active(m: re.Match) -> str:
        verb = m.group(2)
        # Simple de-passivization: remove 'ed' suffix
        if verb.endswith('ed') and len(verb) > 3:
            base = verb[:-2] if not verb[-3] == verb[-4] else verb[:-1]
            if verb.endswith('ied'):
                base = verb[:-3] + 'y'
            elif verb.endswith('ted') and not verb.endswith('ated'):
                base = verb[:-2]
            else:
                base = verb[:-2] if verb.endswith('ed') else verb[:-1]
            return base.capitalize()
        return verb.capitalize()

    sent = re.sub(
        r'\b(should|must|can|will|shall)\s+be\s+(\w+ed)\b',
        _passive_to_active,
        sent,
        flags=re.IGNORECASE,
    )

    return sent


def _compress_relative_clauses(sent: str) -> str:
    """Compress relative clauses for brevity."""
    # "which/that provides/allows/enables" → "providing/allowing/enabling"
    patterns = [
        (r'\bwhich\s+provides?\b', 'providing'),
        (r'\bthat\s+provides?\b', 'providing'),
        (r'\bwhich\s+allows?\b', 'allowing'),
        (r'\bthat\s+allows?\b', 'allowing'),
        (r'\bwhich\s+enables?\b', 'enabling'),
        (r'\bthat\s+enables?\b', 'enabling'),
        (r'\bwhich\s+includes?\b', 'including'),
        (r'\bthat\s+includes?\b', 'including'),
        (r'\bwhich\s+contains?\b', 'containing'),
        (r'\bthat\s+contains?\b', 'containing'),
        (r'\bwhich\s+uses?\b', 'using'),
        (r'\bthat\s+uses?\b', 'using'),
    ]
    for pattern, replacement in patterns:
        sent = re.sub(pattern, replacement, sent, flags=re.IGNORECASE)

    return sent


def _remove_parentheticals(sent: str) -> str:
    """Remove parenthetical asides: (...)  and 'i.e., ...' clauses."""
    # Remove parenthetical content
    sent = re.sub(r'\([^)]{0,100}\)', '', sent)
    # Remove "i.e., ..." up to comma or period
    sent = re.sub(r'\bi\.e\.\s*,?\s*[^,\.]+[,\.]?', '', sent)
    # Remove "e.g., ..." up to comma or period
    sent = re.sub(r'\be\.g\.\s*,?\s*[^,\.]+[,\.]?', '', sent)
    return sent
